/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./*.html",
    "./js/**/*.js",
  ],
  safelist: [
    // Dynamic classes generated in JS template literals
    'bg-green-500', 'bg-green-600', 'bg-green-100',
    'text-green-600', 'text-green-700',
    'bg-blue-100', 'text-blue-700',
    'bg-slate-100', 'text-amber-500',
    'bg-on-surface', 'opacity-75', 'opacity-70',
    'bg-primary/10', 'border-primary/20',
    'bg-surface-container-highest', 'text-on-secondary-fixed-variant',
    'border-2', 'shadow-md',
    'animate-spin',
    'text-error',
  ],
  theme: {
    extend: {
      colors: {
        "primary":                    "#5e0084",
        "on-primary":                 "#ffffff",
        "primary-container":          "#7a22a3",
        "primary-fixed":              "#f7d8ff",
        "primary-fixed-dim":          "#e9b3ff",
        "on-primary-fixed":           "#310048",
        "on-primary-fixed-variant":   "#701499",
        "on-primary-container":       "#e7acff",
        "inverse-primary":            "#e9b3ff",
        "secondary":                  "#5b5d74",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#e0e0fc",
        "on-secondary-container":     "#61637a",
        "on-secondary-fixed":         "#181a2e",
        "secondary-fixed-dim":        "#c3c4df",
        "on-secondary-fixed-variant": "#43455b",
        "tertiary":                   "#6f0e3e",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#8d2955",
        "on-tertiary-container":      "#ffa9c6",
        "on-tertiary-fixed":          "#3e001f",
        "on-tertiary-fixed-variant":  "#821f4c",
        "tertiary-fixed":             "#ffd9e3",
        "tertiary-fixed-dim":         "#ffb0ca",
        "background":                 "#fbf8ff",
        "on-background":              "#161a2e",
        "surface":                    "#fbf8ff",
        "on-surface":                 "#161a2e",
        "on-surface-variant":         "#4e4351",
        "surface-variant":            "#dee1fd",
        "surface-dim":                "#d6d8f4",
        "surface-bright":             "#fbf8ff",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f3f2ff",
        "surface-container":          "#ececff",
        "surface-container-high":     "#e5e6ff",
        "surface-container-highest":  "#dee1fd",
        "surface-tint":               "#8b35b3",
        "surface-muted":              "#F3EBFF",
        "inverse-surface":            "#2b2f44",
        "inverse-on-surface":         "#f0efff",
        "outline":                    "#807382",
        "outline-variant":            "#d1c2d3",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
        "border-light":               "#EEEEEE",
        "border-secondary":           "#DEDFF0",
        "bg-alternate":               "#FAF8FC",
      },
      fontFamily: {
        "display":     ["Hanken Grotesk", "sans-serif"],
        "body":        ["Inter", "sans-serif"],
        "label-md":    ["Inter"],
        "body-md":     ["Inter"],
        "body-lg":     ["Inter"],
        "headline-sm": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "display-lg":  ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "label-md":    ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md":     ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg":     ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg":  ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
